#!/bin/bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$script_dir"

main_file="Core/Src/main.c"
main_file_cpp="Core/Src/main.cpp"
include_file="Core/Inc/main.hpp"
cmake_file="cmake/stm32cubemx/CMakeLists.txt"


if [ -f $main_file ]; then
  cp $main_file $main_file_cpp

  sed -i '/\/\* USER CODE BEGIN Includes \*\//a #include "main_prog.hpp"' $main_file_cpp
  sed -i '/osKernelInitialize();/a   main_prog();' $main_file_cpp
  
  echo "#pragma once" > $include_file
  echo "" >> $include_file
  echo "//File generated by after_ioc.sh" >> $include_file
  echo "" >> $include_file
  echo "#include \"main.h\"" >> $include_file
  echo "" >> $include_file

  sed -n '/\/\* Private variables ---------------------------------------------------------\*\//,/\/\*/p' $main_file_cpp | grep -v '/\*' | while read -r line; do
    if [ ${#line} -eq 1 ]; then
      continue
    else
      echo "extern" $line >> $include_file
    fi
  done


  if grep -q "../../Core/Src/main.c" $cmake_file; then
    sed -i 's|\.\./\.\./Core/Src/main\.c|../../Core/Src/main.cpp|' $cmake_file
  fi

fi