#pragma once

// File generated by StmEpic

#include "main.h"

extern FDCAN_HandleTypeDef hfdcan1;
extern I2C_HandleTypeDef hi2c1;
extern SPI_HandleTypeDef hspi3;
extern TIM_HandleTypeDef htim6;
extern UART_HandleTypeDef huart4;
